name = Home Verde Chile
description = Un layout para usar como home en sitio Cultura Libre
preview = preview.png
template = home_verdechile-layout

regions[branding]       = Marca
regions[principal]	= Barra Superior
regions[slider]		= Slider
regions[navigation]     = Barra de Navegación
regions[highlighted]    = Destacados
regions[help]           = Ayuda
regions[content]        = Contenido
regions[sidebar_media]	= Lateral para Media
regions[sidebar_left]	= Lateral Izquierda
regions[sidebar_right]  = Lateral Derecha
regions[pre_footer_1]   = Pre Footer-1
regions[pre_footer_2]   = Pre Footer-2
regions[pre_footer_3]   = Pre Footer-3
regions[footer]         = Footer


; Stylesheets
stylesheets[all][] = css/layouts/home/home.layout.css
stylesheets[all][] = css/layouts/home/home.layout.no-query.css
stylesheets[all][] = css/layouts/home/verdechile-home.layout.css
